name: ptts
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3

  equatable: ^2.0.5

  flutter_pdfview: ^1.2.7

  file_picker: ^6.1.1

  json_theme: ^4.0.0

  path: ^1.8.3

  get_it: ^7.6.4

  intl: 0.18.1

  floor: ^1.4.2

  flutter_hooks: ^0.20.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/theme/theme.json
